"""initial database schema

Revision ID: 049496d52f0a
Revises: 
Create Date: 2026-08-25 13:53:49.641397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049496d52f0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_forest_associations',
    sa.Column('community_forest_association_id', sa.UUID(), nullable=False),
    sa.Column('community_forest_association_name', sa.String(length=150), nullable=False),
    sa.Column('kenya_forest_service_official_id', sa.UUID(), nullable=False),
    sa.Column('registration_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kenya_forest_service_official_id'], ['users.user_id'], name='fk_cfa_kfs_official', use_alter=True),
    sa.PrimaryKeyConstraint('community_forest_association_id')
    )
    op.create_index(op.f('ix_community_forest_associations_community_forest_association_name'), 'community_forest_associations', ['community_forest_association_name'], unique=True)
    op.create_table('forest_zones',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('cfa_name', sa.String(length=100), nullable=False),
    sa.Column('block_name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('resource_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('tree_survival_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('trees_planted', sa.Integer(), nullable=False),
    sa.Column('trees_surviving', sa.Integer(), nullable=False),
    sa.Column('dead_trees', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_tree_survival_logs_log_id'), 'tree_survival_logs', ['log_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'kenya_forest_service_official', 'community_forest_association_official', 'member', name='user_role'), nullable=False),
    sa.Column('membership_number', sa.String(length=50), nullable=True),
    sa.Column('user_group', sa.Enum('beekeeping', 'tree_planting', 'firewood_collection', 'eco_tourism', name='user_group'), nullable=True),
    sa.Column('registered_by', sa.UUID(), nullable=True),
    sa.Column('community_forest_association_id', sa.UUID(), nullable=True),
    sa.Column('block_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_forest_association_id'], ['community_forest_associations.community_forest_association_id'], name='fk_users_cfa', use_alter=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_membership_number'), 'users', ['membership_number'], unique=True)
    op.create_index(op.f('ix_users_national_id'), 'users', ['national_id'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('activities',
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('activity_name', sa.String(length=100), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_group', sa.Enum('TREE_PLANTING', 'TREE_NURSERY', 'FOREST_CLEANING', 'FOREST_PATROL', 'FIRE_PREVENTION', 'FIRE_FIGHTING', 'FOREST_RESTORATION', 'INVASIVE_SPECIES_CONTROL', 'WATER_SOURCE_PROTECTION', 'WILDLIFE_MONITORING', 'BIODIVERSITY_MONITORING', 'ECO_TOURISM', 'ENVIRONMENTAL_EDUCATION', 'COMMUNITY_AWARENESS', 'TRAINING_WORKSHOP', 'NURSERY_MAINTENANCE', 'TREE_MAINTENANCE', 'AGROFORESTRY', 'SUSTAINABLE_HARVESTING', 'BEEKEEPING', 'CONFLICT_RESOLUTION', 'FOREST_BOUNDARY_MAPPING', 'ILLEGAL_ACTIVITY_REPORTING', 'FOREST_INVENTORY', 'COMMUNITY_MEETING', name='usergroup'), nullable=True),
    sa.Column('expected_attendees', sa.Integer(), nullable=False),
    sa.Column('actual_attendees', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['forest_zones.zone_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('incidents_report',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.Enum('Charcoal_Burning', 'Logging', 'Poaching', 'Others', name='activitytype'), nullable=False),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['forest_zones.zone_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incidents_report_incident_id'), 'incidents_report', ['incident_id'], unique=False)
    op.create_table('permits',
    sa.Column('permit_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('requested_resources', sa.String(length=200), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('permit_number', sa.String(length=50), nullable=True),
    sa.Column('permit_status', sa.String(length=30), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('max_permit', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('payment_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ussd_session_id', sa.String(length=100), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('session_data', sa.String(length=2000), nullable=True),
    sa.Column('session_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('permit_id')
    )
    op.create_index(op.f('ix_permits_checkout_request_id'), 'permits', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_permits_deleted_at'), 'permits', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_permits_member_id'), 'permits', ['member_id'], unique=False)
    op.create_index(op.f('ix_permits_merchant_request_id'), 'permits', ['merchant_request_id'], unique=False)
    op.create_index(op.f('ix_permits_mpesa_receipt_number'), 'permits', ['mpesa_receipt_number'], unique=True)
    op.create_index(op.f('ix_permits_payment_status'), 'permits', ['payment_status'], unique=False)
    op.create_index(op.f('ix_permits_permit_id'), 'permits', ['permit_id'], unique=False)
    op.create_index(op.f('ix_permits_permit_number'), 'permits', ['permit_number'], unique=True)
    op.create_index(op.f('ix_permits_permit_status'), 'permits', ['permit_status'], unique=False)
    op.create_index(op.f('ix_permits_phone_number'), 'permits', ['phone_number'], unique=False)
    op.create_index(op.f('ix_permits_ussd_session_id'), 'permits', ['ussd_session_id'], unique=True)
    op.create_table('registration_payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('community_forest_association_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_forest_association_id'], ['community_forest_associations.community_forest_association_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_registration_payments_checkout_request_id'), 'registration_payments', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_registration_payments_community_forest_association_id'), 'registration_payments', ['community_forest_association_id'], unique=False)
    op.create_index(op.f('ix_registration_payments_member_id'), 'registration_payments', ['member_id'], unique=False)
    op.create_index(op.f('ix_registration_payments_mpesa_receipt'), 'registration_payments', ['mpesa_receipt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_payments_mpesa_receipt'), table_name='registration_payments')
    op.drop_index(op.f('ix_registration_payments_member_id'), table_name='registration_payments')
    op.drop_index(op.f('ix_registration_payments_community_forest_association_id'), table_name='registration_payments')
    op.drop_index(op.f('ix_registration_payments_checkout_request_id'), table_name='registration_payments')
    op.drop_table('registration_payments')
    op.drop_index(op.f('ix_permits_ussd_session_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_phone_number'), table_name='permits')
    op.drop_index(op.f('ix_permits_permit_status'), table_name='permits')
    op.drop_index(op.f('ix_permits_permit_number'), table_name='permits')
    op.drop_index(op.f('ix_permits_permit_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_payment_status'), table_name='permits')
    op.drop_index(op.f('ix_permits_mpesa_receipt_number'), table_name='permits')
    op.drop_index(op.f('ix_permits_merchant_request_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_member_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_deleted_at'), table_name='permits')
    op.drop_index(op.f('ix_permits_checkout_request_id'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_incidents_report_incident_id'), table_name='incidents_report')
    op.drop_table('incidents_report')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_national_id'), table_name='users')
    op.drop_index(op.f('ix_users_membership_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tree_survival_logs_log_id'), table_name='tree_survival_logs')
    op.drop_table('tree_survival_logs')
    op.drop_table('forest_zones')
    op.drop_index(op.f('ix_community_forest_associations_community_forest_association_name'), table_name='community_forest_associations')
    op.drop_table('community_forest_associations')
    # ### end Alembic commands ###
